# Generated by Django 5.1 on 2024-09-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodies',
            name='price',
        ),
    ]
