# Generated by Django 5.1 on 2024-09-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_foodimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodimages',
            old_name='desc',
            new_name='category',
        ),
    ]
