# Generated by Django 5.1 on 2024-09-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_desc_foodimages_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimages',
            name='images',
            field=models.ImageField(upload_to='FoodImages/'),
        ),
    ]
