# Generated by Django 5.1 on 2024-09-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_cart_product_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='cart',
        ),
    ]
